### ISSUE TITLE
Description of pytest finding python test files default patterns

### ISSUE THREAD

**Issue by elit8888** [pluralsight/intro-to-pytest#8]
According to the current pytest official document, the default test files matching patterns are `test_*.py` and `*_test.py`.

But in the current tutorial, https://github.com/pluralsight/intro-to-pytest/blob/master/tutorials/00_empty_test.md, it is stated that:

> when we ran it without any arguments, it searched for tests in all the modules (python files) whose name contained "test", by default.

Reference:
* https://docs.pytest.org/en/stable/reference.html#confval-python_files
* https://docs.pytest.org/en/stable/goodpractices.html#conventions-for-python-test-discovery

**Comment by tenth10th** [comment]
Thanks for the report! (And sorry for the delay) - this issue has been resolved.
